services:
  vpn-us:
    container_name: vpn-us
    image: hosdeburgh2/nord
    restart: unless-stopped
    ports:
      - "9091:9091"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - /etc/nord/config:/etc/nord/config:ro
    environment:
      NORD_OVPN_FILE: nord-us.ovpn

  vpn-trk:
    container_name: vpn-trk
    image: hosdeburgh2/nord
    restart: unless-stopped
    ports:
      - "9090:9090"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    volumes:
      - /etc/nord/config:/etc/nord/config:ro
    environment:
      NORD_OVPN_FILE: nord-trk.ovpn
